Mobile Website
EscHaleem/travel-website pull request #1
Opened 2024-10-12 00:47 UTC by EscHaleem

Mobile website pull request

2024-10-13 15:21 UTC, Devsalmasaeed requested changes

2024-10-13 15:21 UTC, Devsalmasaeed commented on index.html
> +</footer>
#  Navigation should be at the header not footer

2024-10-13 15:21 UTC, Devsalmasaeed commented on styles.css
> +}
Hi @EscHaleem,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
-  **Good use of HTML Semantic** 👍
-  **Professional PR title** 👍
-  **Professional PR description** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

#  Adjust the width of mirror lake card

- The Mirror Lake should have the same width with the remaining cards
![Step 1 screenshot](https://images.tango.us/workflows/63b80b91-68d1-4812-a390-d969f444ecc9/steps/e69bf890-c0fa-4da5-b590-93c8a17d62d9/38054833-6abe-425a-960d-29d866047611.png?crop=focalpoint&fit=crop&fp-x=0.3054&fp-y=0.3898&fp-z=1.0063&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=7&mark-y=7&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTYlMkNGRjc0NDImdz03MjMmaD04OTQmZml0PWNyb3AmY29ybmVyLXJhZGl1cz0xMA%3D%3D)

<br/>

#  Remove the hover effect on all the cards

- Remove the hover effect on each card

![Step 1 screenshot](https://images.tango.us/workflows/ea62b2b5-c97d-4612-beee-40037d0c1c23/steps/84f41706-70a9-4c4f-9c28-c5b8fc6697c9/90acd5a6-8fde-4798-91a9-9d4ab8ec8916.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=5&mark-y=16&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTQlMkNGRjc0NDImdz0zNjYmaD0zMjcmZml0PWNyb3AmY29ybmVyLXJhZGl1cz0xMA%3D%3D)

- This is how your cards should be display

![Step 2 screenshot](https://images.tango.us/workflows/ea62b2b5-c97d-4612-beee-40037d0c1c23/steps/9e31b014-b506-4101-95bb-c481993139ba/0995e656-e21d-4dd6-aa2b-a88e7320c7f9.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n)

<br/>

#  Make sure your ul li are display like the figma design

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-14 09:03 UTC, Xfarouq requested changes
Hi @EscHaleem ,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Please make the sections below to be same as the figma design
- 
![image](https://github.com/user-attachments/assets/b41347d2-9379-4788-bf99-7ebed84efea2)
- allign this section to be central just like in the figma desgin
-
![image](https://github.com/user-attachments/assets/d58a2aad-c38f-41d1-bab4-43d58fdff173)

- Also add readme file

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-22 23:20 UTC, Xfarouq approved these changes
Hi @EscHaleem 

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    <img src="https://media1.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa8sx12d824xrvy8zo8bq3w00f23hoj11gqqzus7q0f&ep=v1_gifs&rid=giphy.gif&ct=g" alt="Remote Collaboration" style="width:100%;">
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
- Add the link to your website in your readme
- Rotate the blue blurry image in the header section to be upright

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-24 00:59 UTC, merged

2024-10-24 08:12 UTC, Devsalmasaeed reviewed
> Hi @EscHaleem
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it!!! Congratulations! 🎉
> 
> ![Remote Collaboration](https://camo.githubusercontent.com/636f8f83cc9fdf8edaad0e2e31e471335a0431c15559750d6ff98dc325075ca5/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f674c7539304f4d6a7a346a3368416b4a6b322f67697068792e6769663f6369643d3437303238666138737831326438323478727679387a6f38627133773030663233686f6a31316771717a7573377130662665703d76315f67696673267269643d67697068792e6769662663743d67)
> ### Highlights
> * ✅ **Professional Readme**
> * ✅ **Good use of Gitflow**
> * ✅ **UI looks like the Figma design**
> * ✅ **Good use of HTML semantics**
> * ✅ **Professional commit messages**

> 
> ### Optional Suggestions
>  * Add  Professional PR title and description for your desktop view
> 
> Cheers and Happy coding! 👏👏👏
> 
> _Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification._